schema = 3

[mod]
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/ttacon/chalk"]
    version = "v0.0.0-20160626202418-22c06c80ed31"
    hash = "sha256-lMdG7YeT0wHF3hGRoZdmMpTCznwD00ThhGbcbXhyTPk="
